services:
  falcon:
    build: .
    container_name: github-falcon
    restart: unless-stopped
    environment:
      - GIT_USER_NAME=elixpoo
      - GIT_USER_EMAIL=elixpoo@gmail.com
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - MODE=loop
    volumes:
      - .:/repo
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
